Add other actions on VMs from the dashboard
UCL-CloudLabs/user-portal pull request #58
Opened 2017-12-05 15:16 UTC by ageorgou

This adds functionality to #43 and will resolve #9 when finished. I don't know whether it's easier to compare this to #43 or to the development branch.

Still work in progress. The basic outline is:
- [x] Get the status of a machine hosted on Azure by querying Azure rather than the DB.
- [ ] Add tasks for starting, stopping and restarting a machine.
- [ ] Refresh the DB status automatically, or think of some other way to ensure it is up-to-date (or at least base decisions on the live status, not the stored one).
- [ ] Implement checks for when actions are applicable/allowed.
- [ ] Always show all buttons on the dashboard, with greyed-out versions for inapplicable actions.
- [ ] Other actions mentioned in #9.

2017-12-05 15:36 UTC, ageorgou commented
Something I forgot to put in the commit message but is worth noting: the version requirement on the Azure SDK packages is because some previous versions do not have all the API methods/fields (in particular `instance_views` was missing, I think). This is the version I've been trying and works.

2018-02-14 18:24 UTC, raquelalegre requested changes
It all seems fine and works on my machine, so just minor changes requested. It'd be nice, but better on a separate PR, to have some more log messages. That'll also give us some information about how the system is being used so we are able to trace problems. I'll create a new issue.

2018-02-14 18:24 UTC, raquelalegre commented on requirements/base.in
> +azure-mgmt-compute>=3.0.1
Comment on why versions < 3.0.1 are not suitable?

2018-02-14 18:24 UTC, raquelalegre commented on src/cloudlabs/app.py
> +    app.current_deployments = {}
Not needed anymore.

2018-02-14 18:24 UTC, raquelalegre commented on src/cloudlabs/azure_tools.py
> +    # TODO are secrets better accessible in a different way?
If I remember well, the Azure secrets were in environment vars and then were moved to the `Secrets` object, so I guess this TODO item was here before the changes starting in line 22. So delete lines 15-21.

2018-02-14 18:24 UTC, raquelalegre commented on src/cloudlabs/azure_tools.py
> +def get_compute_manager(credentials=None, subscription_id=None):
Wouldn't it be nicer to make this utils into a class and then refer to credentials and subscription id as member vars instead of passing them around? That way the code that uses this doesn't need to retrieve and pass around arguments.

2018-02-14 18:24 UTC, raquelalegre commented on src/cloudlabs/context_processors.py
> +    def inject_get_status():
You mentioned this was not needed, so just recording that here because I can't tell! :)

2018-02-14 18:24 UTC, raquelalegre commented on src/cloudlabs/deployer/deployer.py
> +    def restart(self, host):
As per office discussion we are not sure if Azure's `start` does a restart or it's needed that we have an extra start method here.

2018-02-14 18:24 UTC, raquel-ucl commented on src/cloudlabs/tasks/worker.py
> +    print("Destroying {} from task {}".format(host_id, deploy.request.id))
This is probably a leftover debug message that should be a log message when we implement a logger for CloudLabs in a separate PR.

2018-02-15 17:46 UTC, ageorgou commented on requirements/base.in
> +azure-mgmt-compute>=3.0.1
Sorry, mentioned it above but I thought it was in the code too: earlier package versions do not provide the full API. It's possible that some older versions are also OK, but I went with the one I was trying for sure.

2018-02-16 14:25 UTC, ageorgou commented
As per offline discussion, this is enough for this PR. I'll leave remaining tasks (icons, checks for applicable actions, tests?) for another.

2018-02-21 15:53 UTC, raquelalegre approved these changes

2018-02-21 15:58 UTC, merged